-- 1.2
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
SELECT * FROM products5 WHERE id = 101;
COMMIT TRANSACTION;

-- 2.2
BEGIN TRANSACTION;
UPDATE customers5 SET company_name = 'Alphabet' WHERE id = 101;
COMMIT;

-- 3.2
BEGIN TRANSACTION;
INSERT INTO customers5 (id, company_name) VALUES (103, 'Amazon');
COMMIT;